// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
		Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SingleUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleUserRequest) Reset()         { *m = SingleUserRequest{} }
func (m *SingleUserRequest) String() string { return proto.CompactTextString(m) }
func (*SingleUserRequest) ProtoMessage()    {}
func (*SingleUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SingleUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleUserRequest.Unmarshal(m, b)
}
func (m *SingleUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleUserRequest.Marshal(b, m, deterministic)
}
func (m *SingleUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleUserRequest.Merge(m, src)
}
func (m *SingleUserRequest) XXX_Size() int {
	return xxx_messageInfo_SingleUserRequest.Size(m)
}
func (m *SingleUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleUserRequest proto.InternalMessageInfo

func (m *SingleUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserProfileResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileResponse) Reset()         { *m = UserProfileResponse{} }
func (m *UserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponse) ProtoMessage()    {}
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponse.Unmarshal(m, b)
}
func (m *UserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponse.Marshal(b, m, deterministic)
}
func (m *UserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponse.Merge(m, src)
}
func (m *UserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponse.Size(m)
}
func (m *UserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponse proto.InternalMessageInfo

func (m *UserProfileResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SuccessResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*SingleUserRequest)(nil), "SingleUserRequest")
	proto.RegisterType((*UserProfileResponse)(nil), "UserProfileResponse")
	proto.RegisterType((*SuccessResponse)(nil), "SuccessResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0x87, 0x30,
	0x10, 0xc5, 0xf3, 0x2f, 0x8a, 0x72, 0x26, 0x1a, 0x4e, 0x06, 0xc2, 0x64, 0x70, 0x71, 0xb1, 0x24,
	0x38, 0xbb, 0xe8, 0xe0, 0xa8, 0x81, 0xb8, 0xb8, 0x21, 0x9c, 0xa6, 0x09, 0x50, 0xbc, 0x16, 0x3f,
	0xbf, 0xa1, 0x10, 0xa2, 0xc2, 0xd4, 0x7b, 0x6d, 0xdf, 0xfb, 0xf5, 0x15, 0x60, 0x34, 0xc4, 0x72,
	0x60, 0x6d, 0x75, 0x7a, 0x0f, 0xe1, 0x23, 0x53, 0x65, 0xe9, 0xd5, 0x10, 0x17, 0xf4, 0x35, 0x92,
	0xb1, 0x88, 0x70, 0xd4, 0x57, 0x1d, 0xc5, 0x87, 0xab, 0xc3, 0x4d, 0x50, 0xb8, 0x19, 0x23, 0x38,
	0xa6, 0xae, 0x52, 0x6d, 0x2c, 0xdc, 0xe6, 0x2c, 0xd2, 0x6b, 0x08, 0x4b, 0xd5, 0x7f, 0xb6, 0x7f,
	0xec, 0xe7, 0x20, 0x54, 0xb3, 0x98, 0x85, 0x6a, 0xd2, 0x67, 0xb8, 0x9c, 0x8e, 0x5f, 0x58, 0x7f,
	0xa8, 0x96, 0x0a, 0x32, 0x83, 0xee, 0x0d, 0xfd, 0xbf, 0xb6, 0x52, 0xc5, 0x1e, 0xd5, 0xfb, 0x4d,
	0xbd, 0x85, 0x8b, 0x72, 0xac, 0x6b, 0x32, 0x66, 0x0d, 0x4b, 0xe0, 0x94, 0x97, 0x79, 0x89, 0x5c,
	0x75, 0xce, 0x70, 0x36, 0xf1, 0x4b, 0xe2, 0x6f, 0x55, 0x13, 0xe6, 0xe0, 0xcf, 0x95, 0x11, 0xe5,
	0xa6, 0x7b, 0x12, 0xc9, 0xbd, 0xb7, 0x66, 0xe0, 0x3d, 0x91, 0x45, 0x94, 0x9b, 0xb6, 0xfb, 0x86,
	0x87, 0xe0, 0xed, 0x44, 0x66, 0xee, 0x8b, 0xdf, 0x7d, 0xb7, 0xdc, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xde, 0x58, 0x25, 0x6d, 0x77, 0x01, 0x00, 0x00,
}
